[Interface]
Address = 10.99.0.1/30
ListenPort = 51820
PostUp = wg set %i private-key /etc/wireguard/wg0.key

[Peer]
PublicKey = tzfFsEm3r0kW6n7u/QEFwXdQj/zgcu0PzooBBGquGmI=
AllowedIPs = 10.99.0.2/32, 10.10.10.165/32
