[Interface]
Address = 10.99.0.2/30
PostUp = wg set %i private-key /etc/wireguard/wg0.key

[Peer]
PublicKey = NK+QHmv4L4H4nYokZd7AXNKMFwj+KyrUHkTKSitV/Wk=
Endpoint = 203.0.113.10:51820
AllowedIPs = 10.99.0.1/32
PersistentKeepalive = 25
